events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 443 ssl;

        ssl_certificate /etc/nginx/certs/cert.pem;
        ssl_certificate_key /etc/nginx/certs/key.pem;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            add_header blazor-environment Development;
            try_files $uri $uri/ /index.html;
        }
    }
}
