// <auto-generated />
using System;
using BoltonCup.WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BoltonCup.WebAPI.Migrations
{
    [DbContext(typeof(BoltonCupDbContext))]
    [Migration("20260102175830_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("core")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BoltonCup.WebAPI.Data.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birthday");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("HighestLevel")
                        .HasColumnType("text")
                        .HasColumnName("highest_level");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PreferredBeer")
                        .HasColumnType("text")
                        .HasColumnName("preferred_beer");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text")
                        .HasColumnName("profile_picture");

                    b.HasKey("Id");

                    b.ToTable("accounts", "core");
                });

            modelBuilder.Entity("BoltonCup.WebAPI.Data.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwayTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("away_team_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("GameTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("game_time");

                    b.Property<string>("GameType")
                        .HasColumnType("text")
                        .HasColumnName("game_type");

                    b.Property<int?>("HomeTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("home_team_id");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Rink")
                        .HasColumnType("text")
                        .HasColumnName("rink");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_id");

                    b.Property<string>("Venue")
                        .HasColumnType("text")
                        .HasColumnName("venue");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("TournamentId");

                    b.ToTable("games", "core");
                });

            modelBuilder.Entity("BoltonCup.WebAPI.Data.Entities.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Assist1PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("assist1_player_id");

                    b.Property<int?>("Assist2PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("assist2_player_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<int>("GoalPlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("goal_player_id");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Period")
                        .HasColumnType("integer")
                        .HasColumnName("period_number");

                    b.Property<string>("PeriodLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("period_label");

                    b.Property<TimeSpan>("PeriodTimeRemaining")
                        .HasColumnType("interval")
                        .HasColumnName("period_time_remaining");

                    b.HasKey("Id");

                    b.HasIndex("Assist1PlayerId");

                    b.HasIndex("Assist2PlayerId");

                    b.HasIndex("GameId");

                    b.HasIndex("GoalPlayerId");

                    b.ToTable("goals", "core");
                });

            modelBuilder.Entity("BoltonCup.WebAPI.Data.Entities.Penalty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_mins");

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<string>("InfractionName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("infraction_name");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Period")
                        .HasColumnType("integer")
                        .HasColumnName("period_number");

                    b.Property<string>("PeriodLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("period_label");

                    b.Property<TimeSpan>("PeriodTimeRemaining")
                        .HasColumnType("interval")
                        .HasColumnName("period_time_remaining");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("penalties", "core");
                });

            modelBuilder.Entity("BoltonCup.WebAPI.Data.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int?>("JerseyNumber")
                        .HasColumnType("integer")
                        .HasColumnName("jersey_number");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Position")
                        .HasColumnType("text")
                        .HasColumnName("position");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_id");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TournamentId");

                    b.ToTable("players", "core");
                });

            modelBuilder.Entity("BoltonCup.WebAPI.Data.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("abbreviation");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("text")
                        .HasColumnName("banner_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int?>("GmAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("gm_account_id");

                    b.Property<string>("GoalSongUrl")
                        .HasColumnType("text")
                        .HasColumnName("goal_song_url");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NameShort")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_short");

                    b.Property<string>("PenaltySongUrl")
                        .HasColumnType("text")
                        .HasColumnName("penalty_song_url");

                    b.Property<string>("PrimaryColorHex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("primary_hex");

                    b.Property<string>("SecondaryColorHex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("secondary_hex");

                    b.Property<string>("TertiaryColorHex")
                        .HasColumnType("text")
                        .HasColumnName("tertiary_hex");

                    b.Property<int?>("TournamentId")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_id");

                    b.HasKey("Id");

                    b.HasIndex("GmAccountId");

                    b.HasIndex("TournamentId");

                    b.ToTable("teams", "core");
                });

            modelBuilder.Entity("BoltonCup.WebAPI.Data.Entities.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<int?>("GoalieLimit")
                        .HasColumnType("integer")
                        .HasColumnName("goalie_limit");

                    b.Property<string>("GoaliePaymentLink")
                        .HasColumnType("text")
                        .HasColumnName("goalie_payment_link");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPaymentOpen")
                        .HasColumnType("boolean")
                        .HasColumnName("is_payment_open");

                    b.Property<bool>("IsRegistrationOpen")
                        .HasColumnType("boolean")
                        .HasColumnName("is_registration_open");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("SkaterLimit")
                        .HasColumnType("integer")
                        .HasColumnName("skater_limit");

                    b.Property<string>("SkaterPaymentLink")
                        .HasColumnType("text")
                        .HasColumnName("skater_payment_link");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int?>("WinningTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("winning_team_id");

                    b.HasKey("Id");

                    b.ToTable("tournaments", "core");
                });

            modelBuilder.Entity("BoltonCup.WebAPI.Data.Entities.Game", b =>
                {
                    b.HasOne("BoltonCup.WebAPI.Data.Entities.Team", "AwayTeam")
                        .WithMany("AwayGames")
                        .HasForeignKey("AwayTeamId");

                    b.HasOne("BoltonCup.WebAPI.Data.Entities.Team", "HomeTeam")
                        .WithMany("HomeGames")
                        .HasForeignKey("HomeTeamId");

                    b.HasOne("BoltonCup.WebAPI.Data.Entities.Tournament", "Tournament")
                        .WithMany("Games")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("BoltonCup.WebAPI.Data.Entities.Goal", b =>
                {
                    b.HasOne("BoltonCup.WebAPI.Data.Entities.Player", "Assist1Player")
                        .WithMany("PrimaryAssists")
                        .HasForeignKey("Assist1PlayerId");

                    b.HasOne("BoltonCup.WebAPI.Data.Entities.Player", "Assist2Player")
                        .WithMany("SecondaryAssists")
                        .HasForeignKey("Assist2PlayerId");

                    b.HasOne("BoltonCup.WebAPI.Data.Entities.Game", "Game")
                        .WithMany("Goals")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoltonCup.WebAPI.Data.Entities.Player", "Scorer")
                        .WithMany("Goals")
                        .HasForeignKey("GoalPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assist1Player");

                    b.Navigation("Assist2Player");

                    b.Navigation("Game");

                    b.Navigation("Scorer");
                });

            modelBuilder.Entity("BoltonCup.WebAPI.Data.Entities.Penalty", b =>
                {
                    b.HasOne("BoltonCup.WebAPI.Data.Entities.Game", "Game")
                        .WithMany("Penalties")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoltonCup.WebAPI.Data.Entities.Player", "Player")
                        .WithMany("Penalties")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BoltonCup.WebAPI.Data.Entities.Player", b =>
                {
                    b.HasOne("BoltonCup.WebAPI.Data.Entities.Account", "Account")
                        .WithMany("Players")
                        .HasForeignKey("AccountId");

                    b.HasOne("BoltonCup.WebAPI.Data.Entities.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId");

                    b.HasOne("BoltonCup.WebAPI.Data.Entities.Tournament", "Tournament")
                        .WithMany("Players")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Team");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("BoltonCup.WebAPI.Data.Entities.Team", b =>
                {
                    b.HasOne("BoltonCup.WebAPI.Data.Entities.Account", "GeneralManager")
                        .WithMany("ManagedTeams")
                        .HasForeignKey("GmAccountId");

                    b.HasOne("BoltonCup.WebAPI.Data.Entities.Tournament", "Tournament")
                        .WithMany("Teams")
                        .HasForeignKey("TournamentId");

                    b.Navigation("GeneralManager");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("BoltonCup.WebAPI.Data.Entities.Account", b =>
                {
                    b.Navigation("ManagedTeams");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("BoltonCup.WebAPI.Data.Entities.Game", b =>
                {
                    b.Navigation("Goals");

                    b.Navigation("Penalties");
                });

            modelBuilder.Entity("BoltonCup.WebAPI.Data.Entities.Player", b =>
                {
                    b.Navigation("Goals");

                    b.Navigation("Penalties");

                    b.Navigation("PrimaryAssists");

                    b.Navigation("SecondaryAssists");
                });

            modelBuilder.Entity("BoltonCup.WebAPI.Data.Entities.Team", b =>
                {
                    b.Navigation("AwayGames");

                    b.Navigation("HomeGames");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("BoltonCup.WebAPI.Data.Entities.Tournament", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Players");

                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
