<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <!-- required for RazorLight -->
        <PreserveCompilationContext>true</PreserveCompilationContext>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.3.23" />
      <PackageReference Include="AWSSDK.S3" Version="4.0.18.7" />
      <PackageReference Include="Html2Markdown" Version="7.1.2.20" />
      <PackageReference Include="Markdig" Version="0.45.0" />
      <PackageReference Include="RazorLight" Version="2.3.1" />
      <PackageReference Include="Stripe.net" Version="51.0.0" />
      <PackageReference Include="Twilio" Version="7.14.9" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\BoltonCup.Core\src\BoltonCup.Core.csproj" />
      <ProjectReference Include="..\..\BoltonCup.Persistence\src\BoltonCup.Persistence.csproj" />
      <ProjectReference Include="..\..\BoltonCup.Shared\src\BoltonCup.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Email\EmailTemplates\**\*.cshtml" />
    </ItemGroup>

</Project>
