// <auto-generated />
using System;
using BoltonCup.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BoltonCup.Infrastructure.Migrations
{
    [DbContext(typeof(BoltonCupDbContext))]
    [Migration("20260419204537_AddDraftEntities")]
    partial class AddDraftEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("core")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BoltonCup.Core.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("static/defaults/player-avatar.webp")
                        .HasColumnName("avatar_key");

                    b.Property<string>("Banner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("static/defaults/player-banner.jpg")
                        .HasColumnName("banner_key");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birthday");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<int?>("HeightFeet")
                        .HasColumnType("integer")
                        .HasColumnName("height_feet");

                    b.Property<int?>("HeightInches")
                        .HasColumnType("integer")
                        .HasColumnName("height_inches");

                    b.Property<string>("HighestLevel")
                        .HasColumnType("text")
                        .HasColumnName("highest_level");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PreferredBeer")
                        .HasColumnType("text")
                        .HasColumnName("preferred_beer");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.ToTable("accounts", "core");
                });

            modelBuilder.Entity("BoltonCup.Core.BracketChallenge.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<decimal?>("Fee")
                        .HasColumnType("numeric")
                        .HasColumnName("fee");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean")
                        .HasColumnName("is_open");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Link")
                        .HasColumnType("text")
                        .HasColumnName("link");

                    b.Property<string>("Logo")
                        .HasColumnType("text")
                        .HasColumnName("logo");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<DateTime?>("RegistrationCloseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_close_date");

                    b.Property<string>("TermsOfServiceMarkdownContent")
                        .HasColumnType("text")
                        .HasColumnName("terms_of_service_markdown_content");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("bracket_challenge_events", "core");
                });

            modelBuilder.Entity("BoltonCup.Core.BracketChallenge.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AgreedToTermsOfService")
                        .HasColumnType("boolean")
                        .HasColumnName("agreed_terms_of_service");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PaymentId")
                        .HasColumnType("text")
                        .HasColumnName("payment_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "Email")
                        .IsUnique();

                    b.ToTable("bracket_challenge_registrations", "core");
                });

            modelBuilder.Entity("BoltonCup.Core.Draft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("draft_status");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("draft_type");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("drafts", "core");
                });

            modelBuilder.Entity("BoltonCup.Core.DraftOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("DraftId")
                        .HasColumnType("integer")
                        .HasColumnName("draft_id");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<int>("Pick")
                        .HasColumnType("integer")
                        .HasColumnName("pick_number");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_id");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("DraftId", "Pick")
                        .IsUnique();

                    b.HasIndex("DraftId", "TeamId")
                        .IsUnique();

                    b.ToTable("draft_orders", "core");
                });

            modelBuilder.Entity("BoltonCup.Core.DraftPick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("DraftId")
                        .HasColumnType("integer")
                        .HasColumnName("draft_id");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<int>("OverallPick")
                        .HasColumnType("integer")
                        .HasColumnName("overall_pick_number");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("DraftId", "OverallPick")
                        .IsUnique();

                    b.HasIndex("DraftId", "PlayerId")
                        .IsUnique();

                    b.ToTable("draft_picks", "core");
                });

            modelBuilder.Entity("BoltonCup.Core.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwayTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("away_team_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("GameTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("game_time");

                    b.Property<string>("GameType")
                        .HasColumnType("text")
                        .HasColumnName("game_type");

                    b.Property<int?>("HomeTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("home_team_id");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Rink")
                        .HasColumnType("text")
                        .HasColumnName("rink");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_id");

                    b.Property<string>("Venue")
                        .HasColumnType("text")
                        .HasColumnName("venue");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("TournamentId");

                    b.ToTable("games", "core");
                });

            modelBuilder.Entity("BoltonCup.Core.GameHighlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("video_id");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("VideoId")
                        .IsUnique();

                    b.ToTable("game_highlights", "core");
                });

            modelBuilder.Entity("BoltonCup.Core.GameStar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<int>("StarRank")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId", "GameId")
                        .IsUnique();

                    b.HasIndex("StarRank", "GameId")
                        .IsUnique();

                    b.ToTable("game_stars", "core");
                });

            modelBuilder.Entity("BoltonCup.Core.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Assist1PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("assist1_player_id");

                    b.Property<int?>("Assist2PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("assist2_player_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<int>("GoalPlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("goal_player_id");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Period")
                        .HasColumnType("integer")
                        .HasColumnName("period_number");

                    b.Property<string>("PeriodLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("period_label");

                    b.Property<TimeSpan>("PeriodTimeRemaining")
                        .HasColumnType("interval")
                        .HasColumnName("period_time_remaining");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("Assist1PlayerId");

                    b.HasIndex("Assist2PlayerId");

                    b.HasIndex("GameId");

                    b.HasIndex("GoalPlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("goals", "core");
                });

            modelBuilder.Entity("BoltonCup.Core.GoalieStat", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<int>("Assists")
                        .HasColumnType("integer")
                        .HasColumnName("assists");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birthday");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("GameRink")
                        .HasColumnType("text")
                        .HasColumnName("game_rink");

                    b.Property<DateTime>("GameTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("game_time");

                    b.Property<string>("GameType")
                        .HasColumnType("text")
                        .HasColumnName("game_type");

                    b.Property<string>("GameVenue")
                        .HasColumnType("text")
                        .HasColumnName("game_venue");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("games_played");

                    b.Property<int>("Goals")
                        .HasColumnType("integer")
                        .HasColumnName("goals");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("integer")
                        .HasColumnName("goals_against");

                    b.Property<double>("GoalsAgainstAverage")
                        .HasColumnType("double precision")
                        .HasColumnName("goals_against_average");

                    b.Property<int?>("JerseyNumber")
                        .HasColumnType("integer")
                        .HasColumnName("jersey_number");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("OpponentAbbreviation")
                        .HasColumnType("text")
                        .HasColumnName("opponent_abbreviation");

                    b.Property<int>("OpponentId")
                        .HasColumnType("integer")
                        .HasColumnName("opponent_id");

                    b.Property<string>("OpponentLogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("opponent_logo_url");

                    b.Property<string>("OpponentName")
                        .HasColumnType("text")
                        .HasColumnName("opponent_name");

                    b.Property<string>("OpponentNameShort")
                        .HasColumnType("text")
                        .HasColumnName("opponent_name_short");

                    b.Property<double>("PenaltyMinutes")
                        .HasColumnType("double precision")
                        .HasColumnName("penalty_minutes");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<string>("Position")
                        .HasColumnType("text")
                        .HasColumnName("position");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text")
                        .HasColumnName("profile_picture");

                    b.Property<double>("SavePercentage")
                        .HasColumnType("double precision")
                        .HasColumnName("save_percentage");

                    b.Property<int>("Saves")
                        .HasColumnType("integer")
                        .HasColumnName("saves");

                    b.Property<int>("ShotsAgainst")
                        .HasColumnType("integer")
                        .HasColumnName("shots_against");

                    b.Property<int>("Shutouts")
                        .HasColumnType("integer")
                        .HasColumnName("shutouts");

                    b.Property<string>("TeamAbbreviation")
                        .HasColumnType("text")
                        .HasColumnName("team_abbreviation");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<string>("TeamLogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("team_logo_url");

                    b.Property<string>("TeamName")
                        .HasColumnType("text")
                        .HasColumnName("team_name");

                    b.Property<string>("TeamNameShort")
                        .HasColumnType("text")
                        .HasColumnName("team_name_short");

                    b.Property<bool>("TournamentActive")
                        .HasColumnType("boolean")
                        .HasColumnName("tournament_active");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_id");

                    b.Property<string>("TournamentName")
                        .HasColumnType("text")
                        .HasColumnName("tournament_name");

                    b.Property<int>("Wins")
                        .HasColumnType("integer")
                        .HasColumnName("wins");

                    b.HasKey("GameId", "PlayerId");

                    b.HasIndex("OpponentId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable((string)null);

                    b.ToView("mv_goalie_game_logs", "core");
                });

            modelBuilder.Entity("BoltonCup.Core.InfoGuide", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("MarkdownContent")
                        .HasColumnType("text")
                        .HasColumnName("markdown_content");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int?>("TournamentId")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_id");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId")
                        .IsUnique()
                        .HasFilter("tournament_id IS NOT NULL");

                    b.ToTable("info_guides", "core");
                });

            modelBuilder.Entity("BoltonCup.Core.Penalty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_mins");

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<string>("InfractionName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("infraction_name");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Period")
                        .HasColumnType("integer")
                        .HasColumnName("period_number");

                    b.Property<string>("PeriodLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("period_label");

                    b.Property<TimeSpan>("PeriodTimeRemaining")
                        .HasColumnType("interval")
                        .HasColumnName("period_time_remaining");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("penalties", "core");
                });

            modelBuilder.Entity("BoltonCup.Core.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<bool>("AgreedToCodeOfConduct")
                        .HasColumnType("boolean")
                        .HasColumnName("agreed_code_of_conduct");

                    b.Property<bool>("AgreedToCommunicationConsent")
                        .HasColumnType("boolean")
                        .HasColumnName("agreed_communication_consent");

                    b.Property<bool>("AgreedToConcussionWaiver")
                        .HasColumnType("boolean")
                        .HasColumnName("agreed_concussion_waiver");

                    b.Property<bool>("CanPlayEitherPosition")
                        .HasColumnType("boolean")
                        .HasColumnName("can_play_either_position");

                    b.Property<string>("Captaincy")
                        .HasColumnType("text")
                        .HasColumnName("captaincy");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Friends")
                        .HasColumnType("text")
                        .HasColumnName("friends");

                    b.Property<int?>("JerseyNumber")
                        .HasColumnType("integer")
                        .HasColumnName("jersey_number");

                    b.Property<string>("JerseySize")
                        .HasColumnType("text")
                        .HasColumnName("jersey_size");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("PaymentId")
                        .HasColumnType("text")
                        .HasColumnName("payment_id");

                    b.Property<string>("Position")
                        .HasColumnType("text")
                        .HasColumnName("position");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_id");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("TournamentId");

                    b.HasIndex("AccountId", "TournamentId")
                        .IsUnique();

                    b.ToTable("players", "core");
                });

            modelBuilder.Entity("BoltonCup.Core.SkaterStat", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<int>("Assists")
                        .HasColumnType("integer")
                        .HasColumnName("assists");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birthday");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("GameRink")
                        .HasColumnType("text")
                        .HasColumnName("game_rink");

                    b.Property<DateTime>("GameTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("game_time");

                    b.Property<string>("GameType")
                        .HasColumnType("text")
                        .HasColumnName("game_type");

                    b.Property<string>("GameVenue")
                        .HasColumnType("text")
                        .HasColumnName("game_venue");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("games_played");

                    b.Property<int>("Goals")
                        .HasColumnType("integer")
                        .HasColumnName("goals");

                    b.Property<int?>("JerseyNumber")
                        .HasColumnType("integer")
                        .HasColumnName("jersey_number");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("OpponentAbbreviation")
                        .HasColumnType("text")
                        .HasColumnName("opponent_abbreviation");

                    b.Property<int>("OpponentId")
                        .HasColumnType("integer")
                        .HasColumnName("opponent_id");

                    b.Property<string>("OpponentLogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("opponent_logo_url");

                    b.Property<string>("OpponentName")
                        .HasColumnType("text")
                        .HasColumnName("opponent_name");

                    b.Property<string>("OpponentNameShort")
                        .HasColumnType("text")
                        .HasColumnName("opponent_name_short");

                    b.Property<double>("PenaltyMinutes")
                        .HasColumnType("double precision")
                        .HasColumnName("penalty_minutes");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<string>("Position")
                        .HasColumnType("text")
                        .HasColumnName("position");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text")
                        .HasColumnName("profile_picture");

                    b.Property<string>("TeamAbbreviation")
                        .HasColumnType("text")
                        .HasColumnName("team_abbreviation");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<string>("TeamLogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("team_logo_url");

                    b.Property<string>("TeamName")
                        .HasColumnType("text")
                        .HasColumnName("team_name");

                    b.Property<string>("TeamNameShort")
                        .HasColumnType("text")
                        .HasColumnName("team_name_short");

                    b.Property<bool>("TournamentActive")
                        .HasColumnType("boolean")
                        .HasColumnName("tournament_active");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_id");

                    b.Property<string>("TournamentName")
                        .HasColumnType("text")
                        .HasColumnName("tournament_name");

                    b.HasKey("GameId", "PlayerId");

                    b.HasIndex("OpponentId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable((string)null);

                    b.ToView("mv_skater_game_logs", "core");
                });

            modelBuilder.Entity("BoltonCup.Core.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("abbreviation");

                    b.Property<string>("Banner")
                        .HasColumnType("text")
                        .HasColumnName("banner_key");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int?>("GmAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("gm_account_id");

                    b.Property<string>("GoalSong")
                        .HasColumnType("text")
                        .HasColumnName("goal_song_key");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Logo")
                        .HasColumnType("text")
                        .HasColumnName("logo_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NameShort")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_short");

                    b.Property<string>("PenaltySong")
                        .HasColumnType("text")
                        .HasColumnName("penalty_song_key");

                    b.Property<string>("PrimaryColorHex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("primary_hex");

                    b.Property<string>("SecondaryColorHex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("secondary_hex");

                    b.Property<string>("TertiaryColorHex")
                        .HasColumnType("text")
                        .HasColumnName("tertiary_hex");

                    b.Property<int?>("TournamentId")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_id");

                    b.HasKey("Id");

                    b.HasIndex("GmAccountId");

                    b.HasIndex("TournamentId");

                    b.ToTable("teams", "core");
                });

            modelBuilder.Entity("BoltonCup.Core.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<int?>("GoalieLimit")
                        .HasColumnType("integer")
                        .HasColumnName("goalie_limit");

                    b.Property<string>("GoaliePaymentLink")
                        .HasColumnType("text")
                        .HasColumnName("goalie_payment_link");

                    b.Property<decimal?>("GoalieRegistrationFee")
                        .HasColumnType("numeric")
                        .HasColumnName("goalie_registration_fee");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPaymentOpen")
                        .HasColumnType("boolean")
                        .HasColumnName("is_payment_open");

                    b.Property<bool>("IsRegistrationOpen")
                        .HasColumnType("boolean")
                        .HasColumnName("is_registration_open");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Logo")
                        .HasColumnType("text")
                        .HasColumnName("logo_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("SkaterLimit")
                        .HasColumnType("integer")
                        .HasColumnName("skater_limit");

                    b.Property<string>("SkaterPaymentLink")
                        .HasColumnType("text")
                        .HasColumnName("skater_payment_link");

                    b.Property<decimal?>("SkaterRegistrationFee")
                        .HasColumnType("numeric")
                        .HasColumnName("skater_registration_fee");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int?>("WinningTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("winning_team_id");

                    b.HasKey("Id");

                    b.HasIndex("WinningTeamId");

                    b.ToTable("tournaments", "core");
                });

            modelBuilder.Entity("BoltonCup.Core.TournamentRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer")
                        .HasColumnName("current_step");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_complete");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Payload")
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_id");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.HasIndex("AccountId", "TournamentId")
                        .IsUnique();

                    b.ToTable("tournament_registrations", "core");
                });

            modelBuilder.Entity("BoltonCup.Core.BracketChallenge.Registration", b =>
                {
                    b.HasOne("BoltonCup.Core.BracketChallenge.Event", "BracketChallenge")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BracketChallenge");
                });

            modelBuilder.Entity("BoltonCup.Core.Draft", b =>
                {
                    b.HasOne("BoltonCup.Core.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("BoltonCup.Core.DraftOrder", b =>
                {
                    b.HasOne("BoltonCup.Core.Draft", "Draft")
                        .WithMany("DraftOrders")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoltonCup.Core.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Draft");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BoltonCup.Core.DraftPick", b =>
                {
                    b.HasOne("BoltonCup.Core.Draft", "Draft")
                        .WithMany("DraftPicks")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoltonCup.Core.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.HasOne("BoltonCup.Core.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Draft");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BoltonCup.Core.Game", b =>
                {
                    b.HasOne("BoltonCup.Core.Team", "AwayTeam")
                        .WithMany("AwayGames")
                        .HasForeignKey("AwayTeamId");

                    b.HasOne("BoltonCup.Core.Team", "HomeTeam")
                        .WithMany("HomeGames")
                        .HasForeignKey("HomeTeamId");

                    b.HasOne("BoltonCup.Core.Tournament", "Tournament")
                        .WithMany("Games")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("BoltonCup.Core.GameHighlight", b =>
                {
                    b.HasOne("BoltonCup.Core.Game", "Game")
                        .WithMany("Highlights")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoltonCup.Core.Player", "Player")
                        .WithMany("GameHighlights")
                        .HasForeignKey("PlayerId");

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BoltonCup.Core.GameStar", b =>
                {
                    b.HasOne("BoltonCup.Core.Game", "Game")
                        .WithMany("Stars")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoltonCup.Core.Player", "Player")
                        .WithMany("Stars")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BoltonCup.Core.Goal", b =>
                {
                    b.HasOne("BoltonCup.Core.Player", "Assist1Player")
                        .WithMany("PrimaryAssists")
                        .HasForeignKey("Assist1PlayerId");

                    b.HasOne("BoltonCup.Core.Player", "Assist2Player")
                        .WithMany("SecondaryAssists")
                        .HasForeignKey("Assist2PlayerId");

                    b.HasOne("BoltonCup.Core.Game", "Game")
                        .WithMany("Goals")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoltonCup.Core.Player", "Scorer")
                        .WithMany("Goals")
                        .HasForeignKey("GoalPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoltonCup.Core.Team", "Team")
                        .WithMany("Goals")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assist1Player");

                    b.Navigation("Assist2Player");

                    b.Navigation("Game");

                    b.Navigation("Scorer");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BoltonCup.Core.GoalieStat", b =>
                {
                    b.HasOne("BoltonCup.Core.Game", "Game")
                        .WithMany("GoalieGameLogs")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoltonCup.Core.Team", "Opponent")
                        .WithMany()
                        .HasForeignKey("OpponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoltonCup.Core.Player", "Player")
                        .WithMany("GoalieGameLogs")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoltonCup.Core.Team", "Team")
                        .WithMany("GoalieGameLogs")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Opponent");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BoltonCup.Core.InfoGuide", b =>
                {
                    b.HasOne("BoltonCup.Core.Tournament", "Tournament")
                        .WithOne("InfoGuide")
                        .HasForeignKey("BoltonCup.Core.InfoGuide", "TournamentId");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("BoltonCup.Core.Penalty", b =>
                {
                    b.HasOne("BoltonCup.Core.Game", "Game")
                        .WithMany("Penalties")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoltonCup.Core.Player", "Player")
                        .WithMany("Penalties")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoltonCup.Core.Team", "Team")
                        .WithMany("Penalties")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BoltonCup.Core.Player", b =>
                {
                    b.HasOne("BoltonCup.Core.Account", "Account")
                        .WithMany("Players")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoltonCup.Core.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId");

                    b.HasOne("BoltonCup.Core.Tournament", "Tournament")
                        .WithMany("Players")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Team");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("BoltonCup.Core.SkaterStat", b =>
                {
                    b.HasOne("BoltonCup.Core.Game", "Game")
                        .WithMany("SkaterGameLogs")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoltonCup.Core.Team", "Opponent")
                        .WithMany()
                        .HasForeignKey("OpponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoltonCup.Core.Player", "Player")
                        .WithMany("SkaterGameLogs")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoltonCup.Core.Team", "Team")
                        .WithMany("SkaterGameLogs")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Opponent");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BoltonCup.Core.Team", b =>
                {
                    b.HasOne("BoltonCup.Core.Account", "GeneralManager")
                        .WithMany("ManagedTeams")
                        .HasForeignKey("GmAccountId");

                    b.HasOne("BoltonCup.Core.Tournament", "Tournament")
                        .WithMany("Teams")
                        .HasForeignKey("TournamentId");

                    b.Navigation("GeneralManager");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("BoltonCup.Core.Tournament", b =>
                {
                    b.HasOne("BoltonCup.Core.Team", "WinningTeam")
                        .WithMany()
                        .HasForeignKey("WinningTeamId");

                    b.Navigation("WinningTeam");
                });

            modelBuilder.Entity("BoltonCup.Core.TournamentRegistration", b =>
                {
                    b.HasOne("BoltonCup.Core.Account", "Account")
                        .WithMany("TournamentRegistrations")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoltonCup.Core.Tournament", "Tournament")
                        .WithMany("Registrations")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("BoltonCup.Core.Account", b =>
                {
                    b.Navigation("ManagedTeams");

                    b.Navigation("Players");

                    b.Navigation("TournamentRegistrations");
                });

            modelBuilder.Entity("BoltonCup.Core.BracketChallenge.Event", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("BoltonCup.Core.Draft", b =>
                {
                    b.Navigation("DraftOrders");

                    b.Navigation("DraftPicks");
                });

            modelBuilder.Entity("BoltonCup.Core.Game", b =>
                {
                    b.Navigation("GoalieGameLogs");

                    b.Navigation("Goals");

                    b.Navigation("Highlights");

                    b.Navigation("Penalties");

                    b.Navigation("SkaterGameLogs");

                    b.Navigation("Stars");
                });

            modelBuilder.Entity("BoltonCup.Core.Player", b =>
                {
                    b.Navigation("GameHighlights");

                    b.Navigation("GoalieGameLogs");

                    b.Navigation("Goals");

                    b.Navigation("Penalties");

                    b.Navigation("PrimaryAssists");

                    b.Navigation("SecondaryAssists");

                    b.Navigation("SkaterGameLogs");

                    b.Navigation("Stars");
                });

            modelBuilder.Entity("BoltonCup.Core.Team", b =>
                {
                    b.Navigation("AwayGames");

                    b.Navigation("GoalieGameLogs");

                    b.Navigation("Goals");

                    b.Navigation("HomeGames");

                    b.Navigation("Penalties");

                    b.Navigation("Players");

                    b.Navigation("SkaterGameLogs");
                });

            modelBuilder.Entity("BoltonCup.Core.Tournament", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("InfoGuide");

                    b.Navigation("Players");

                    b.Navigation("Registrations");

                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
